### ISSUE TITLE
The graphical interface became a blank page since DSM 7.1

### ISSUE THREAD

**Issue by zlorn** [davidcava/shadowsocks-libev-dsm#12]
Hi there, when I upgraded dsm to version 7.1-42661, there was a problem with the graphical interface, it became a blank page, do you have time to update the software to fix this problem? thank you very much!

**Comment by davidcava** [comment]
Yes right 对的. Some libraries I was relying on have disappeared from DSM. I will try to fix that but cannot say when.

**Comment by davidcava** [comment]
ok fixed now, please check!

**Comment by zlorn** [comment]
> ok fixed now, please check!

Great! It works now. Thank you!
