### ISSUE TITLE
DS918+ and V2ray plugin

### ISSUE THREAD

**Issue by amirr1361** [davidcava/shadowsocks-libev-dsm#14]
Hi,

Thank you for your effort for developing this application.

How to run v2ray plugin to configure the Shadowsocks on Synology DS918? DSM 7.1

Also, I can't see any files in etc folder , how can I configure it as a server?

**Comment by davidcava** [comment]
I assume the x86_64 is the proper package.
Kindly check the explainations on GitHub main page for configuration. Let me know if something does not work or not clear.

Basically you store your config files into /var/packages/shadowsocks-libev/etc. Names must be: ss-local.json ss-tunnel.json ss-redir.json or ss-server.json. Using the app icon within DSM allows to change those files.  For v2ray, you need to follow the general documentation on how to configure the plugin. For example, that could be adding the following options into ss-local.json:
  "plugin":"v2ray-plugin",
  "plugin_opts":"tls;host=amirr1361.me"

**Comment by davidcava** [comment]
closing as no other question for 3 weeks
