### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by SHADEworldGAD** [davidcava/shadowsocks-libev-dsm#17]
Hi. At startup it gives an error: "Startup of shadowsocks-libev ss-local failed for config file /var/packages/shadowsocks/etc/ss-local.json"

My config:
{
 "server":"121.*.*.*",
 "server_port":1****,
 "local_address":"127.0.0.1",
 "local_port":1080,
 "password":"df********",
 "timeout":300,
 "method":"xchacha20-ietf-poly1305"
}

What is the problem?

**Comment by davidcava** [comment]
Hi
You can ssh to your synology box and check the logs for the service with: sudo journalctl -u pkg-ss-local@ss-local

**Comment by SHADEworldGAD** [comment]
NAS systemd[1]: [/usr/local/lib/systemd/system/pkg-ss-local@.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'
NAS systemd[1]: [/usr/local/lib/systemd/system/pkg-ss-local@.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'
NAS systemd[1]: Starting Shadowsocks-Libev Custom Client Service for ss/local...
NAS systemd[1]: pkg-ss-local@ss-local.service: control process exited, code=exited status=255
NAS systemd[1]: Failed to start Shadowsocks-Libev Custom Client Service for ss/local.
NAS systemd[1]: Unit pkg-ss-local@ss-local.service entered failed state.
NAS systemd[1]: pkg-ss-local@ss-local.service failed.
NAS systemd[1]: [/usr/local/lib/systemd/system/pkg-ss-local@.service:9] Unknown lvalue 'AmbientCapabilities' in section 'Service'

**Comment by davidcava** [comment]
Well not sure about what goes wrong. What is your NAS model?
You can try to remove the line AmbientCapabilities from /usr/local/lib/systemd/system/pkg-ss-local@.service and see if that's better.
You can also try to launch manually and see what feedback you get:
/var/packages/shadowsocks-libev/target/bin/ss-local -c /var/packages/shadowsocks-libev/etc/ss-local.json

**Comment by SHADEworldGAD** [comment]
I use XPEnology (DS918+).
After deleting the "AmbientCapabilities" line, nothing changed.
When you run it manually, it gives an error: "ERROR: Invalid config path".

**Comment by davidcava** [comment]
All right I don't know, no idea about XPEnology. I assume this is DSM  7.something, as we are talking systemd?
Symptoms seems similar to [this issue](https://github.com/shadowsocks/shadowsocks-libev/issues/1780)  so maybe check this thread and see if it applies.
If you find how to hack and fix, tell me what you needed to do, I will see if this is possible to implement within the packaged solution.

**Comment by SHADEworldGAD** [comment]
>  I assume this is DSM 7.something, as we are talking systemd?

Yes, DSM 7.2.1-69057 Update 4.
Where the config.json file is located?

**Comment by davidcava** [comment]
Should be /var/packages/shadowsocks-libev/etc/ss-local.json, as used when launching manually by command line /var/packages/shadowsocks-libev/target/bin/ss-local -c /var/packages/shadowsocks-libev/etc/ss-local.json

**Comment by davidcava** [comment]
Hi
I installed a XPEnology (DS918+) with DSM 7.2.1-69057 Update 4 on VirtualBox.
And then tried shadowsocks-libev-dsm 3.3.5-3, with your exact config.
And... no problem for me, that works as expected.
So I am closing the issue for now, but please provide feedback if you find anything.
D.
