### ISSUE TITLE
Can open router but no internet access

### ISSUE THREAD

**Issue by Orangeadambell** [davidcava/shadowsocks-libev-dsm#18]
Hi David, I installed the package on my DS720+. I ran ss-server with the default configuration. After port forwarding 1995, I was able to log in to my home router on my cellphone (cellular network) using Potatso. However, I couldn't get any other internet access such as google. Is there anything I did not implement? Thanks.
{
	"server":"0.0.0.0",
	"server_port":1995,
	"password":"********",
	"timeout":60,
	"method":"chacha20-ietf-poly1305",
	"fast_open": false,
	"mode": "tcp_only"
}

**Comment by davidcava** [comment]
Hi
Using the Synology as a ss server routing to Internet is not something I have done.
Maybe you need to activate routing on the synology, using sudo /sbin/sysctl -w -q net.ipv4.ip_forward=1 (+ a few more, see script redirect.sh, but this one should be a good start).
David

**Comment by Orangeadambell** [comment]
Hi David, I enabled routing on the synology and tried changing the server from 0.0.0.0 to my nas ip (192.168.0.10). However, I still can only access private networks (router, nas, remote desktop etc...) from the cellular network. I found this reply from the previous post (https://github.com/davidcava/shadowsocks-libev-dsm/issues/4#issuecomment-756429805) that trying to do the same thing. I changed my server address from nas ip to wan ip (192.168.0.1) but couldn't get it running. I am a noob but I guess this makes sense as shadowsocks server physically running on my nas. Let me know if you have any suggestions. Thanks~

**Comment by Orangeadambell** [comment]
Hi after trying everything such as specifying the local address, local port, ddns vs public ip, etc... It turned out to be the potatso setup problem. Somehow I need to specify DNS (1.1.1.1 is slightly fast in my case) in the app for it to work. There is no need to specify anything else other than the default setting in ss-server.json (great tool btw).
