### ISSUE TITLE
Can‘t start on DS216J

### ISSUE THREAD

**Issue by yxj93** [davidcava/shadowsocks-libev-dsm#3]
Shadowsocks-libev: Nothing started: check config file(s) ss-(local|server|redir|tunnel|manager)[-confname].json in: /var/packages/shadowsocks-libev/etc

How can i fix this problem？

**Comment by davidcava** [comment]
Have you created a valid config file in /var/packages/shadowsocks-libev/etc for either ss-local or ss-server? Either manually or by using the app? If yes can you provide it (do not show real server address or password)?

**Comment by davidcava** [comment]
Then you can try connecting via ssh and launching manually to see if any error message:
`PATH=/var/packages/shadowsocks-libev/target/bin LD_LIBRARY_PATH=/var/packages/shadowsocks-libev/target/lib /var/packages/shadowsocks-libev/target/bin/ss-local -c /var/packages/shadowsocks-libev/etc/ss-local.json`
(replace ss-local by ss-server or ss-redir depending on what you need)
