### ISSUE TITLE
Note able to start

### ISSUE THREAD

**Issue by wmar** [davidcava/shadowsocks-libev-dsm#5]
![image](https://user-images.githubusercontent.com/33446638/68573754-4dd1d900-04a3-11ea-8efa-35bc542cabb2.png)

**Comment by davidcava** [comment]
You need to setup the config file before the service can start.
After installation you should have a new Shadowsocks app now installed in your apps (blue paper plane). Click on it and configure at least 1 config file so that you can start the service.
Or manually create a config file through ssh into /var/package/shadowsocks-libev/etc
I will try to make the message a bit more clear in that aspect.
David

**Comment by wmar** [comment]
I tried to click on it (RUN) from DS-216II+ that doesnt come up config
screen.
William

**Comment by davidcava** [comment]
You cannot click "Run" before setting a configuration file.
For that you need to get out of the package installation screen and open the main application menu by clicking top left in DSM (the 4 cubes). Here you should see the blue paper plane app named shadowsocks-libev. Click this one to access the configuration files if you do not want to use the command line.

**Comment by wmar** [comment]
Interesting,  it isn't showed in the "4 cubes" menu.  The apps is installed
under package center and only show in it.

[image: image.png]
William

**Comment by davidcava** [comment]
ok I understand the confusion. I had that once but I would need to investigate where it comes from.
I think I could make the app appear by simply disconnecting and reconnecting to DSM from the browser.

**Comment by wmar** [comment]
Seems not my case, I had tried both reboot the NAS and using different browser to access it.  Still not able to see the apps

**Comment by davidcava** [comment]
ok I can reproduce, it was too long I did not try to reinstall from scratch without any config file existing. I need to investigate.

**Comment by davidcava** [comment]
I published an updated version, hope this solves the issue

**Comment by davidcava** [comment]
closing as no feedback on the fix
