### ISSUE TITLE
admin required to operate

### ISSUE THREAD

**Issue by frakman1** [davidcava/shadowsocks-libev-dsm#8]
My Synology has the **admin** account intentionally disabled for security reasons. There are users with admin privileges. 
When I try to launch the app while logged in  with admin privileges, I get this error telling me that I _must_ be logged in as **admin**.

![image](https://user-images.githubusercontent.com/5826484/103929583-84c56e00-50eb-11eb-9a46-05af0a347c01.png)

**Can you please remove the requirement for admin login?**

 I can control every other aspect of the NAS with my account (including setting up a VPN server) so I dont' see why this should be any different.

**Comment by davidcava** [comment]
removed the control in 3.3.5, without extended checks. Tell me how it goes.

**Comment by frakman1** [comment]
Thank you! I just installed it and it works now.
