### ISSUE TITLE
DS720+

### ISSUE THREAD

**Issue by harryhou1101** [davidcava/shadowsocks-libev-dsm#9]
Hi davidcava, 
Is there will be a package for DS720+ (geminilake)? 

THX!

**Comment by davidcava** [comment]
yes there is
David

Le lun. 11 janv. 2021 à 17:56, harryhou1101 <notifications@github.com> a
écrit :

**Comment by Zloi78** [comment]
Hello!
And for DS220 + (also geminilake)

Thank you in advance!

**Comment by davidcava** [comment]
Hello
For some reason, the geminilake dev environment does not want to compile the package.
But from what I understand, all the following architectures are supposed to be identical: apollolake, avoton, braswell, broadwell, broadwellnk, broadwellntb, broadwellntbap, bromolow, cedarview,coffeelake, denverton, geminilake, grantley, kvmx64, purley, skylaked, v1000, x86.
Can you please try the broadwell package instead and tell me if that works?

**Comment by Zloi78** [comment]
> 
> 
> Hello
> For some reason, the geminilake dev environment does not want to compile the package.
> But from what I understand, all the following architectures are supposed to be identical: apollolake, avoton, braswell, broadwell, broadwellnk, broadwellntb, broadwellntbap, bromolow, cedarview,coffeelake, denverton, geminilake, grantley, kvmx64, purley, skylaked, v1000, x86.
> Can you please try the broadwell package instead and tell me if that works?

When installing the shadowsocks-libev-broadwell-3.3.5-1.spk package, I get a message: "The package is not supported on the Synology NAS platform or is incompatible with the current DSM version".
Thanks for the answer anyway. I chose docker use case.

**Comment by davidcava** [comment]
ok, yes I need to figure out how to properly generate the packages based on the architecture, and the DSM documentation is pretty unclear

**Comment by davidcava** [comment]
ok I think I got it. You can try the x86_64 binary, it should work

**Comment by Zloi78** [comment]
> 
> 
> ok I think I got it. You can try the x86_64 binary, it should work
Yes. Everything works now. Thank you!
![2021-01-24_233128](https://user-images.githubusercontent.com/6129745/105638405-a02aca00-5e9c-11eb-8048-db423646602b.jpg)
